<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
	 <SupportedOSPlatformVersion>10.0.10240.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>Resources\TabPaint.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64</Platforms>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
	<PublishReadyToRun>true</PublishReadyToRun>
	<TieredCompilation>true</TieredCompilation> 
	<TieredCompilationQuickJit>true</TieredCompilationQuickJit>
	 <!-- <PublishSingleFile>true</PublishSingleFile>单文件 -->
  
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>3</WarningLevel>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <WarningLevel>3</WarningLevel>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>3</WarningLevel>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <WarningLevel>3</WarningLevel>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\deprecated_functions.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Cursors\Closedhand.cur" />
    <None Remove="Resources\Cursors\Eyedropper.cur" />
    <None Remove="Resources\Cursors\Openhand.cur" />
    <None Remove="Resources\help-1.gif" />
    <None Remove="Resources\help-2.gif" />
    <None Remove="Resources\help-3.gif" />
    <None Remove="Resources\TabPaint_64x64.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\help-3.gif" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Cursors\Closedhand.cur" />
    <Resource Include="Resources\Cursors\Eyedropper.cur" />
    <Resource Include="Resources\Cursors\Openhand.cur" />
    <Resource Include="Resources\help-1.gif" />
    <Resource Include="Resources\help-2.gif" />
    <Resource Include="Resources\TabPaint.ico" />
  </ItemGroup>

  <ItemGroup>
  
    <Resource Include="Resources\TabPaint_64x64.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MicaWPF" Version="6.3.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.20.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="Svg.Skia" Version="3.4.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.10" />
    <PackageReference Include="System.Management" Version="10.0.2" />
    <PackageReference Include="WriteableBitmapEx" Version="1.6.9" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="pyocr\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
